Endgame
BigMacintosh/Parking pull request #184
Opened 2020-02-27 14:14 UTC by ChrisGora

The `GameEnd` event now includes a list of winners. The GUI will inform you if you won based on this list. The `Eliminate` event already included a list of eliminated players. The GUI will now inform you if you have been eliminated.

Resolves #182

2020-02-27 15:05 UTC, Keywarn submitted a review, later dismissed
<3

2020-02-27 17:30 UTC, RileyEv requested changes
Some of the logic doesn't work. We also never finished the work on `disconnect-hotfix` hence why it wasn't merged into master, so disconnecting of players also doesn't work.

2020-02-27 17:30 UTC, RileyEv commented on ProjectFiles/Assets/Scripts/Game/RoundManager.cs
> +            if (roundNumber < RoundProperties.MaxRounds && world.GetNumPlayers() > 1)
This logic isn't going to work. The world.GetNumPlayers won't go below 1 until the players have been eliminated, so whatever happens there will have to be one more round with just 1 player before the game ends.

2020-02-27 17:30 UTC, RileyEv commented on ProjectFiles/Assets/Scripts/Game/RoundManager.cs
> +                numberOfSpaces = (int) Math.Ceiling(world.GetNumPlayers() * RoundProperties.SpacesToPlayersRatio);
Doesn't work with 2 players. 

ceil(2 * 0.6) = 2 so there's always two spaces for two player
```suggestion
                numberOfSpaces = (int) Math.Floor(world.GetNumPlayers() * RoundProperties.SpacesToPlayersRatio);
```

2020-02-27 17:35 UTC, ChrisGora commented
Either change it rn or I can try to change it tomorrow at some point before 2pm

2020-02-28 10:06 UTC, ChrisGora commented
Gonna fix shit now

2020-02-28 10:08 UTC, RileyEv commented
I’ll be in uni for just after 11 so when your done come in and we can test it

Many Thanks

Riley Evans
On 28 Feb 2020, 10:06 +0000, Chris Gora <notifications@github.com>, wrote:
> Gonna fix shit now
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-02-28 10:18 UTC, ChrisGora commented
maybe

Warmest Regards,
Krzysztof

2020-02-28 10:19 UTC, RileyEv commented
It was my automatic signature in my email 🙈

Many Thanks

Riley Evans
On 28 Feb 2020, 10:18 +0000, Chris Gora <notifications@github.com>, wrote:
> maybe
> Warmest Regards,
> Krzysztof
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-02-28 10:21 UTC, jackbondpreston commented
good luck at the demo today

Season's greetings,
Jack Bond-Preston

2020-02-28 10:22 UTC, RileyEv commented
Good luck in your interview today

Many thanks,

Riley Evans
 www.rileyevans.co.uk
On 28 Feb 2020, 10:22 +0000, Jack Bond-Preston <notifications@github.com>, wrote:
> good luck at the demo today
> Season's greetings,
> Jack Bond-Preston
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-02-28 17:54 UTC, RileyEv approved these changes

2020-02-28 17:54 UTC, merged