Fix HUD to dynamically add to controllable car.
BigMacintosh/Parking pull request #50
Opened 2019-11-27 12:38 UTC by RileyEv

When car is spawned as controllable the HUD, now uses it's velocity.

Resolves #39

2019-11-27 12:40 UTC, ChrisGora submitted a review, later dismissed

2019-11-27 12:43 UTC, ChrisGora requested changes
Disable the HUD on the server

2019-11-27 13:08 UTC, RileyEv commented
Now changed so that the HUD is instantiated in the ClientGameLoop. Needs to be made into a class, for controlling the HUD at some point.

2019-11-28 14:23 UTC, RileyEv reviewed
Looks good 😊

2019-11-28 14:24 UTC, ChrisGora approved these changes

2019-12-18 14:21 UTC, merged